### ISSUE TITLE
Any interaction with `vvvvalvalval/scope-capture`?

### ISSUE THREAD

**Issue by piotr-yuxuan** [BrunoBonacci/rdt#2]
Hello,

Thank you very much for this great library. The idea of having tests as repl contexts reminds me of a library that allows to remember such contexts:

https://github.com/vvvvalvalval/scope-capture

Any chance `rdt` and `scope-capture` could smoothly interact with each other? :-)

**Comment by BrunoBonacci** [comment]
Hi @piotr-yuxuan ,

that's an interesting library. For my own REPL development I have an unpublished library which is a toolbox of macros and functions to help with common tasks during the REPL driven development.

One of these utilities is called `deflet` and it is a macro that turns the `let` bindings into `def` to simplify the debugging and development. Maybe at some point, I will publish this library if you are interested.

On the other hand, here I'm trying to do the opposite. I'm trying to convert the `def` into local binding so that there are no issues with tests that use multiple threads.

You can look at the `def->let-flat` or `def->let-nested` macros to see what's happening. https://github.com/BrunoBonacci/rdt/blob/main/src/com/brunobonacci/rdt.clj#L38-L53
